// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf_Cc-y3FLIDtJIJgyXoZWhZpjGo7V_n4',
    appId: '1:494793376606:web:1b8906acdcd3e4b3eb45cf',
    messagingSenderId: '494793376606',
    projectId: 'nuntius-97a7c',
    authDomain: 'nuntius-97a7c.firebaseapp.com',
    storageBucket: 'nuntius-97a7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrwGZgmtQ5O97HGVTNoBVLZKP9P2SjKg',
    appId: '1:494793376606:android:f514b66b0f3739dbeb45cf',
    messagingSenderId: '494793376606',
    projectId: 'nuntius-97a7c',
    storageBucket: 'nuntius-97a7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxhQvOR0glfMwP0FbfM0Xgn9_QoDn5pI',
    appId: '1:494793376606:ios:8bdc1c27bdc49da2eb45cf',
    messagingSenderId: '494793376606',
    projectId: 'nuntius-97a7c',
    storageBucket: 'nuntius-97a7c.appspot.com',
    iosClientId: '494793376606-19ufaap8em6ch0ov3jrt3rbb4tn13rbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuntius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxhQvOR0glfMwP0FbfM0Xgn9_QoDn5pI',
    appId: '1:494793376606:ios:8bdc1c27bdc49da2eb45cf',
    messagingSenderId: '494793376606',
    projectId: 'nuntius-97a7c',
    storageBucket: 'nuntius-97a7c.appspot.com',
    iosClientId: '494793376606-19ufaap8em6ch0ov3jrt3rbb4tn13rbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuntius',
  );
}
